apiVersion: v1
kind: ConfigMap
metadata:
  name: attendence-config
  namespace: attendencenamespace
data:
  # Non-sensitive configuration
  APP_NAME: "Attendance System"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
