apiVersion: v1
kind: Secret
metadata:
  name: attendence-secrets
  namespace: attendencenamespace
type: Opaque
stringData:
  DB_URL: "mongodb+srv://shahryar:qUTKMSlkk0Xuhlq0@cluster0.72le5.mongodb.net/?appName=Cluster0"
