apiVersion: v1
kind: Service
metadata:
  name: attendence-service
  namespace: attendencenamespace
spec:
  selector:
    app: attendenceops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
